CREATE OR REPLACE PROCEDURE JRGY_PRO_UPDATE_USUARIO(
    COD_USUARIO_P NUMBER,
    NOMBRE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_P VARCHAR2,
    EMAIL_USUARIO_P VARCHAR2,
    TELEFONO_USUARIO_P NUMBER,
    COD_MANAGER_P NUMBER DEFAULT NULL
)
IS
    USUARIO_EXISTE NUMBER;
    MANAGER_EXISTE NUMBER;
BEGIN
    LOCK TABLE JRGY_USUARIO IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO USUARIO_EXISTE FROM JRGY_USUARIO WHERE COD_USUARIO = COD_USUARIO_P;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20002, 'El COD_USUARIO proporcionado no existe.');
    END;

    IF COD_MANAGER_P IS NOT NULL THEN
        BEGIN
            SELECT 1 INTO MANAGER_EXISTE FROM JRGY_USUARIO WHERE COD_USUARIO = COD_MANAGER_P;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20003, 'El COD_MANAGER proporcionado no existe.');
        END;
    END IF;

    UPDATE JRGY_USUARIO SET 
    NOMBRE_USUARIO = NOMBRE_USUARIO_P,
    APELLIDO1_USUARIO = APELLIDO1_USUARIO_P,
    APELLIDO2_USUARIO = APELLIDO2_USUARIO_P,
    EMAIL_USUARIO = EMAIL_USUARIO_P,
    TELEFONO_USUARIO = TELEFONO_USUARIO_P,
    COD_MANAGER = COD_MANAGER_P
    WHERE COD_USUARIO = COD_USUARIO_P;

    COMMIT;
    
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20004, 'Error al actualizar usuario.');
END;
/