CREATE OR REPLACE PROCEDURE JRGY_PRO_DELETE_USUARIO(
    COD_USUARIO_P NUMBER
)
IS
    USUARIO_EXISTE NUMBER;
BEGIN
    LOCK TABLE JRGY_USUARIO IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO USUARIO_EXISTE FROM JRGY_USUARIO WHERE COD_USUARIO = COD_USUARIO_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'El COD_USUARIO proporcionado no existe.');
    END;

    DELETE FROM JRGY_USUARIO WHERE COD_USUARIO = COD_USUARIO_P;
    COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20004, 'Error al eliminar usuario.');
END;
/