CREATE OR REPLACE PROCEDURE JRGY_PRO_INSERTAR_USUARIO(
    NOMBRE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_P VARCHAR2,
    EMAIL_USUARIO_P VARCHAR2,
    TELEFONO_USUARIO_P NUMBER,
    COD_MANAGER_P NUMBER DEFAULT NULL
)
IS
    USUARIO_EXISTE NUMBER;
BEGIN
    LOCK TABLE JRGY_USUARIO IN ROW EXCLUSIVE MODE;

    IF COD_MANAGER_P IS NOT NULL THEN
        BEGIN
            SELECT 1 INTO USUARIO_EXISTE FROM JRGY_USUARIO WHERE COD_USUARIO = COD_MANAGER_P;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20001, 'El COD_MANAGER proporcionado no existe.');
        END;
    END IF;

    INSERT INTO JRGY_USUARIO(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO, EMAIL_USUARIO,
    TELEFONO_USUARIO, COD_MANAGER)
    VALUES(JRGY_SEQ_PK_USUARIO.NEXTVAL, NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P, EMAIL_USUARIO_P, TELEFONO_USUARIO_P, COD_MANAGER_P);
    COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20004, 'Error al insertar usuario.');
END;
/