-- CREACION DE LAS TABLAS

CREATE TABLE JRGY_USUARIO(
    COD_USUARIO NUMBER,
    NOMBRE_USUARIO VARCHAR2(50),
    APELLIDO1_USUARIO VARCHAR2(50),
    APELLIDO2_USUARIO VARCHAR2(50),
    EMAIL_USUARIO VARCHAR2(100),
    TELEFONO_USUARIO NUMBER,
    COD_MANAGER NUMBER,

    CONSTRAINT PK_JRGY_USUARIO PRIMARY KEY(COD_USUARIO),
    CONSTRAINT FK_JRGY_USUARIO_MANAGER FOREIGN KEY(COD_MANAGER) REFERENCES JRGY_USUARIO(COD_USUARIO)
);

/*
    AL PRIMER INGRESO DE UN USUARIO, EL CAMPO DE COD MANAGER DEBE SER NULO YA QUE NO HAY NINGUN USUARIO PREVIO CREADO,
    PARA EVITAR ERRORES EN LA INSERCION DEL PRIMER USUARIO.
*/

CREATE TABLE JRGY_REGION(
    COD_REGION NUMBER,
    NOMBRE_REGION VARCHAR2(50),

    CONSTRAINT PK_JRGY_REGION PRIMARY KEY(COD_REGION)
);

CREATE TABLE JRGY_CIUDAD(
    COD_CIUDAD NUMBER,
    NOMBRE_CIUDAD VARCHAR2(50),
    COD_REGION NUMBER,

    CONSTRAINT PK_JRGY_CIUDAD PRIMARY KEY(COD_CIUDAD),
    CONSTRAINT FK_JRGY_CIUDAD_REGION FOREIGN KEY(COD_REGION) REFERENCES JRGY_REGION(COD_REGION)
);

CREATE TABLE JRGY_COMUNA(
    COD_COMUNA NUMBER,
    NOMBRE_COMUNA VARCHAR2(50),
    COD_CIUDAD NUMBER,

    CONSTRAINT PK_JRGY_COMUNA PRIMARY KEY(COD_COMUNA),
    CONSTRAINT FK_JRGY_COMUNA_CIUDAD FOREIGN KEY(COD_CIUDAD) REFERENCES JRGY_CIUDAD(COD_CIUDAD)
);

CREATE TABLE JRGY_CALLE(
    COD_CALLE NUMBER,
    NOMBRE_CALLE VARCHAR2(80),
    NRO_CALLE NUMBER,
    COD_COMUNA NUMBER,

    CONSTRAINT PK_JRGY_CALLE PRIMARY KEY(COD_CALLE),
    CONSTRAINT FK_JRGY_CALLE_COMUNA FOREIGN KEY(COD_COMUNA) REFERENCES JRGY_COMUNA(COD_COMUNA)
);

CREATE TABLE JRGY_EMPLEADO(
    COD_EMPLEADO NUMBER,
    CARGO_EMPLEADO VARCHAR2(50),
    FECHA_CONTRATACION DATE,
    SALARIO NUMBER,
    COMISION NUMBER,
    COD_USUARIO NUMBER,
    COD_MANAGER NUMBER,

    CONSTRAINT PK_JRGY_EMPLEADO PRIMARY KEY(COD_EMPLEADO),
    CONSTRAINT FK_JRGY_EMPLEADO_USUARIO FOREIGN KEY(COD_USUARIO) REFERENCES JRGY_USUARIO(COD_USUARIO),
    CONSTRAINT FK_JRGY_EMPLEADO_USUARIO_MANAGER FOREIGN KEY(COD_MANAGER) REFERENCES JRGY_USUARIO(COD_USUARIO)
);

CREATE TABLE JRGY_PROVEEDOR(
    COD_PROVEEDOR NUMBER,
    NOMBRE_PROVEEDOR VARCHAR2(50),
    TELEFONO_PROVEEDOR NUMBER,
    COD_REGION NUMBER,

    CONSTRAINT PK_JRGY_PROVEEDOR PRIMARY KEY(COD_PROVEEDOR),
    CONSTRAINT FK_JRGY_PROVEEDOR_REGION FOREIGN KEY(COD_REGION) REFERENCES JRGY_REGION(COD_REGION)
);

CREATE TABLE JRGY_BODEGA(
    COD_BODEGA NUMBER,
    CANTIDAD_EXISTENTE NUMBER,

    CONSTRAINT PK_JRGY_BODEGA PRIMARY KEY(COD_BODEGA)
);

CREATE TABLE JRGY_PAGO_HABITACION(
    COD_PAGO_HABITACION NUMBER,
    FECHA_PAGO_HABITACION DATE,

    CONSTRAINT PK_JRGY_PAGO_HABITACION PRIMARY KEY(COD_PAGO_HABITACION)
);

CREATE TABLE JRGY_HABITACION(
    COD_HABITACION NUMBER,
    NRO_HABITACION NUMBER,
    NRO_PERSONA NUMBER,
    FECHA_DESEOCUPACION DATE,
    ESTADO VARCHAR2(30),
    PRECIO_HABITACION NUMBER,
    COD_USUARIO NUMBER,

    CONSTRAINT PK_JRGY_HABITACION PRIMARY KEY(COD_HABITACION),
    CONSTRAINT FK_JRGY_HABITACION_USUARIO FOREIGN KEY(COD_USUARIO) REFERENCES JRGY_USUARIO(COD_USUARIO)
);

CREATE TABLE JRGY_PRODUCTO(
    COD_PRODUCTO NUMBER,
    NOMBRE_PRODUCTO VARCHAR2(50),
    DESCRIPCION_PRODUCTO VARCHAR2(200),
    TIPO_PRODUCTO VARCHAR2(20),
    PRECIO_PRODUCTO NUMBER,
    CANTIDAD_PRODUCTO NUMBER,
    STOCK_PRODUCTO NUMBER,
    COD_BODEGA NUMBER,

    CONSTRAINT PK_JRGY_PRODUCTO PRIMARY KEY(COD_PRODUCTO),
    CONSTRAINT FK_JRGY_PRODUCTO_BODEGA FOREIGN KEY(COD_BODEGA) REFERENCES JRGY_BODEGA(COD_BODEGA)
);

CREATE TABLE JRGY_PEDIDO(
    COD_PEDIDO NUMBER,
    VALOR_TOTAL NUMBER,
    FECHA_PEDIDO DATE,
    COD_PROVEEDOR NUMBER,

    CONSTRAINT PK_JRGY_PEDIDO PRIMARY KEY(COD_PEDIDO),
    CONSTRAINT FK_JRGY_PEDIDO_PROVEEDOR FOREIGN KEY(COD_PROVEEDOR) REFERENCES JRGY_PROVEEDOR(COD_PROVEEDOR)
);

CREATE TABLE JRGY_DETALLE_PEDIDO(
    COD_PEDIDO NUMBER,
    COD_USUARIO NUMBER,
    NOMBRE_PRODUCTO VARCHAR2(50),
    CANTIDAD_PEDIDO NUMBER,
    PRECIO_COMPRA NUMBER,
    PRECIO_TOTAL NUMBER,

    CONSTRAINT PK_JRGY_DETALLE_PEDIDO PRIMARY KEY(COD_PEDIDO, COD_USUARIO),
    CONSTRAINT FK_JRGY_DETALLE_PEDIDO_PEDIDO FOREIGN KEY(COD_PEDIDO) REFERENCES JRGY_PEDIDO(COD_PEDIDO),
    CONSTRAINT FK_JRGY_DETALLE_PEDIDO_USUARIO FOREIGN KEY(COD_USUARIO) REFERENCES JRGY_USUARIO(COD_USUARIO)
);

CREATE TABLE JRGY_DETALLE_PAGO_HABITACION(
    COD_PAGO_HABITACION NUMBER,
    COD_HABITACION NUMBER,
    FECHA_ESTADIA DATE,
    CANTIDAD_HABITACION NUMBER,
    PRECIO_HABITACION NUMBER,
    PRECIO_TOTAL NUMBER,

    CONSTRAINT PK_JRGY_DETALLE_PAGO_HABITACION PRIMARY KEY(COD_PAGO_HABITACION, COD_HABITACION),
    CONSTRAINT FK_JRGY_DETALLE_PAGO_HABITACION_PAGO_HABITACION FOREIGN KEY(COD_PAGO_HABITACION) REFERENCES JRGY_PAGO_HABITACION(COD_PAGO_HABITACION),
    CONSTRAINT FK_JRGY_DETALLE_PAGO_HABITACION_HABITACION FOREIGN KEY(COD_HABITACION) REFERENCES JRGY_HABITACION(COD_HABITACION)
);

CREATE TABLE JRGY_VENTA(
    COD_VENTA NUMBER,
    COD_USUARIO NUMBER,

    CONSTRAINT PK_JRGY_VENTA PRIMARY KEY(COD_VENTA),
    CONSTRAINT FK_JRGY_VENTA_USUARIO FOREIGN KEY(COD_USUARIO) REFERENCES JRGY_USUARIO(COD_USUARIO)
);

CREATE TABLE JRGY_DETALLE_VENTA(
    COD_VENTA NUMBER,
    COD_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    PRECIO_PRODUCTO NUMBER,
    PRECIO_TOTAL NUMBER,
    FECHA_VENTA DATE,

    CONSTRAINT PK_JRGY_DETALLE_VENTA PRIMARY KEY(COD_VENTA, COD_PRODUCTO),
    CONSTRAINT FK_JRGY_DETALLE_VENTA_VENTA FOREIGN KEY(COD_VENTA) REFERENCES JRGY_VENTA(COD_VENTA),
    CONSTRAINT FK_JRGY_DETALLE_VENTA_PRODUCTO FOREIGN KEY(COD_PRODUCTO) REFERENCES JRGY_PRODUCTO(COD_PRODUCTO)
);
-- COMPILACION: 16 BUENAS DE 16

DROP TABLE JRGY_DETALLE_VENTA;
DROP TABLE JRGY_VENTA;
DROP TABLE JRGY_DETALLE_PAGO_HABITACION;
DROP TABLE JRGY_DETALLE_PEDIDO;
DROP TABLE JRGY_PEDIDO;
DROP TABLE JRGY_PRODUCTO;
DROP TABLE JRGY_HABITACION;
DROP TABLE JRGY_PAGO_HABITACION;
DROP TABLE JRGY_BODEGA;
DROP TABLE JRGY_PROVEEDOR;
DROP TABLE JRGY_EMPLEADO;
DROP TABLE JRGY_USUARIO;