CREATE OR REPLACE PROCEDURE JRGY_PRO_CRUD_EMPLEADO(
    ACCION_P VARCHAR2,
    COD_EMPLEADO_P NUMBER,
    CARGO_EMPLEADO_P VARCHAR2,
    FECHA_CONTRATACION_P DATE,
    SALARIO_P NUMBER,
    COMISION_P NUMBER

)
IS
BEGIN
    LOCK TABLE JRGY_EMPLEADO IN EXCLUSIVE MODE;

    IF ACCION_P = 'I' THEN
        INSERT INTO JRGY_EMPLEADO(CARGO_EMPLEADO, FECHA_CONTRATACION, SALARIO, COMISION)
        VALUES(CARGO_EMPLEADO_P, FECHA_CONTRATACION_P, SALARIO_P, COMISION_P, COD_USUARIO_P, COD_MANAGER_P);
    ELSIF ACCION_P = 'U' THEN
        UPDATE JRGY_EMPLEADO
        SET CARGO_EMPLEADO = CARGO_EMPLEADO_P,
            FECHA_CONTRATACION = FECHA_CONTRATACION_P,
            SALARIO = SALARIO_P,
            COMISION = COMISION_P
        WHERE COD_EMPLEADO = COD_EMPLEADO_P;
    ELSIF ACCION_P = 'D' THEN
        DELETE FROM JRGY_EMPLEADO
        WHERE COD_EMPLEADO = COD_EMPLEADO_P;
    END IF;
    COMMIT;

    EXCEPTION
        WHEN PROGRAM_ERROR THEN
            RAISE_APPLICATION_ERROR(-2001, 'USAR I,U, D EN ACCION');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-2002, 'ERROR EN PROCEDIMIENTO CRUD EMPLEADO');
    ROLLBACK;
END;
/

/*
    AGREGAR LA FORMA DE QUE EL CODIGO DEL EMPLEADO SEA EL MIMSO QUE EL ASIGNADO AL USUARIO, PERO PARA DIFERENCIAR ENTRE CLIENTE Y EMPLEADO, SE HARÁ MEDIANTE QUIEN TIENE ASIGNADO UN MANAGER (JEFE) Y QUIEN NO (CLIENTE).

    TABLA USUARIO
    ID 10  JUAN PEREZ
    ID 12 FERNANDO LOPEZ


    TABLA EMPLEADO
    ID 10 JUAN PEREZ
    ID 100 MARIA GOMEZ (MANAGER)


*/